### ISSUE TITLE
`embed-resource` can silently fail to embed a resource

### ISSUE THREAD

**Issue by Jasper-Bekkers** [nabijaczleweli/rust-embed-resource#70]
Thankfully this isn't a huge deal for me, and we've debugged and fixed this quite easily, but I figured it was worth to at least give the feedback.

We're cross compiling our windows binaries from linux while pretending to be the msvc toolchain, this is all fine and dandy and it's even supported by this crate through the not_windows path, so far so good!

However, it turned out we didn't have a symlink to llvm-rc in our path and therefor we silently fall out of this branch:

https://github.com/nabijaczleweli/rust-embed-resource/blob/81bead8a0f7f4419235882728ca0733e3a94fceb/src/non_windows.rs#L67-L79

I think in hindsight it would've been nice to either have some log output so we can see from the build.rs script's output that it's tried llvm-rc and failed, or to have a Result<> returned all the way up from `compile` so we can `.expect` on it and see it even sooner. Regardless: have a nice day and thanks for the useful crate :-)

**Comment by nabijaczleweli** [comment]
I don't think build scripts can log at all unfortunately, otherwise this would definitely be a "embed-resource: no compiler" warning.

Actually it looks like cargo 0.50.1 contains https://github.com/rust-lang/cargo/commit/590c803ff1 with `cargo:warning=gaming`... except it only logs it on panic. Which defeats the point of a warning.

Historically, this wasn't return-communicated because I think a significant proportion of manifests are icon-only (or similarly optional). That said returning a NotWindows/Ok/NoAttempt/Failure enum that can upcasted with `.manifest_optional()`/`.manifest_required()` -> Result is the best of both worlds probably? You could have `embed_resource::compile().manifest_requred().expect()`, [http](https://github.com/thecoshman/http/blob/master/http-manifest.rc) could have `embed_resource::compile().manifest_optional().expect()` which is basically equivalent to `embed_resource::compile();`.

**Comment by Jasper-Bekkers** [comment]
> I don't think build scripts can log at all unfortunately, otherwise this would definitely be a "embed-resource: no compiler" warning.

Yeah those only get logged on panic so it's not the most useful, `eprintln` and `dbg` also only show up with a panic in build scripts. `build.rs` is not the most friendly thing to debug...

I like your suggestion of returning an object that can communicate the expectations. In our case, we needed to set a use of common controls in the manifest, otherwise the application wouldn't start due to a missing entrypoint, meaning that I'd love to run ".expect" on the result to catch silent build failures here. Indeed, if you only need an icon, it's not super important.

**Comment by nabijaczleweli** [comment]
Actually don't, the three entirely unrelated compilation environments, 2 of which I can only iterate on CI are kicking my ass.
